## Basic Configuration
baseurl = "https://vojtechsedlak.com/"
languageCode = "en"
theme = "hyde-hyde"
title = "Vojtech Sedlak"
googleAnalytics = "UA-115799778-1"
disqusShortname = "vojtechsedlak-com"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$","_files$","_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

## Site Settings
[params]
    author = "Vojtech Sedlak"
    title = "Vojtech Sedlak"
    description = "Desc"
    authorimage = "/img/hugo.png"
    dateformat = "Mon, Jan 2, 2006"
    highlightjs = true
    highlightjsstyle = "atom-one-light"

## Social Accounts
[params.social]
    github = "vojtechsedlak"
    linkedin = "vsedlak"
    twitter = "vojtechsedlak"
    email = "sedlak.vn+blog@gmail.com"

## Main Menu
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 100
    url = "/about/"
[[menu.main]]
    name = "Posts"
    identifier = "posts"
    weight = 200
    url = "/post/"