name = "hyde-hyde"
license = "MIT"
licenselink = "https://github.com/htr3n/hyde-hyde/blob/master/LICENSE.md"
description = "A forked/derived version of Hyde"
tags = ["Blog", "Theme", "Hyde", "Highlight.js"]
features = ["blog", "theme", "highlight.js"]
min_version = "0.33"

[author]
    name = "htr3n"
    homepage = "https://htr3n.github.io"

# If Porting existing theme
[original]
    author =  "spf13"
    homepage = "http://spf13.com/"
    repo = "https://github.com/spf13/hyde"


